name: NodeJS with Webpack

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 22
              uses: actions/setup-node@v4
              with:
                  node-version: 22
            - name: Build
              env:
                  CI: false
              run: |
                  npm install
                  npm run build
            - name: "Upload to GitHub pages branch gh-pages"
              uses: JamesIves/github-pages-deploy-action@4.1.7
              with:
                  branch: gh-pages
                  folder: build
